### PR TITLE
Create CsIEventListenerXml.h

### PR DESCRIPTION
**Pull request by manojthakursharma**

### CODE REVIEW

**Comment by dayjaby** [comment]
In the .deb that I installed, this file is already included. What exactly did you install?

**Comment by manojthakursharma** [comment]
Dear David,

I have install all .deb files. gtk, libudev after  all these I used this "sudo
apt-get install libboost-all-dev libpugixml-dev".
command and installed successfully ... When I used following command " sudo
pip install zebra-scanner" It is showing errors..Errors screenshot is
attached . (Please find attachment).... If you know its solution please
help me. I look forward to hear from you.  Thank you

Regards,
Manoj Thakur

**Comment by dayjaby** [comment]
> Errors screenshot is attached . (Please find attachment)

Where is the screenshot?

And apart from that, I won't accept the CsIEventListenerXml.h file as it is copyrighted. But it I think it can be found directly if it's installed manually into /usr/include

**Comment by dayjaby** [comment]
The file is contained within the zebra sdk and is not part of this repository due to licensing issues.

**Pull request closed without merging**
